CREATE TABLE `` (
	`id`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`email`	TEXT NOT NULL UNIQUE,
	`password`	TEXT NOT NULL
);

CREATE TABLE `login_attempts` (
	`id`	INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE,
	`user_email`	TEXT NOT NULL,
	`timestamp`	NUMERIC NOT NULL
);